database:
  #MySQL, MongoDB
  type: 'MySQL'
  host: 'host'
  port: 3306
  dataBase: 'dataBase'
  user: 'user'
  password: 'password'
module:
  cloudNet:
    v2: false
    v3: false
    teamGroups:
      - 'Admin'
      - 'Mod'
      - 'Sup'
  report:
    enable: true
  antiBot:
    enable: true
    maxAccounts: 2
    #https://iphub.info/apiKey/newFree Create your own free key
    vpnKey: 'Nzg2OTppa2dhbkJOdVZTZms3ODdHNDdjZzRZclhFNWJPSFdTWg=='
permissions:
  banCommand: 'ban.command.ban'
  unbanCommand: 'ban.command.unban'
  loginCommand: 'ban.command.login'
  updateNotify: 'ban.notify.update'
  banBypass: 'ban.bypass'
  banEveryone: 'ban.op'
settings:
  ipBan: true
  banBypassing:
    name: 'Ban bypassing'
    duration: '-1'
  banReasons: 4
  banReason:
    1:
      name: 'Clientmods'
      duration: '30 d'
      points: 50
      isReportReason: true
    2:
      name: 'Chat'
      duration: '2 d'
      points: 10
      isReportReason: true
    3:
      name: 'Advertising'
      duration: '-1'
      points: 50
      isReportReason: true
    4:
      name: 'Other'
      duration: '7 d'
      points: 25
      isReportReason: true
  muteReasons: 2
  muteReason:
    1:
      name: 'Provocation'
      duration: '5 d'
      points: 50
      isReportReason: true
    2:
      name: 'Chat'
      duration: '2 d'
      points: 10
      isReportReason: true